service: func-bicscan-api-proxy

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: ap-northeast-2

functions:
  proxy:
    handler: handler.proxy

plugins:
  - serverless-python-requirements
